name: AWS Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
  runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Configure AWS Credentials
uses: aws-actions/configure-aws-credentials@v4
with:
  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
  aws-region: us-east-1
- name: Test AWS Access
run: |
aws s3 ls
